@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam actorStyle awesome
mainframe **Create resource**

actor Administrator
control ResourceController
participant "ResourceServiceCRUD" as ResourceServiceCRUD
activate ResourceServiceCRUD #DarkSalmon
entity Resource
boundary ResourceRepository
database Biblioteca

Administrator --> ResourceController: Create new resource with areaThemeId, resourceType, Status, name and date
ResourceController-->ResourceServiceCRUD
ResourceServiceCRUD-->Resource
Resource-->ResourceRepository
ResourceRepository-->Biblioteca
Biblioteca-->ResourceServiceCRUD
ResourceServiceCRUD-->ResourceController
Administrator <-- ResourceController: Resource creation confirmation

@enduml