@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam actorStyle awesome
mainframe **Create resource**

actor Administrator
control ResourceController
entity Resource
participant "ResourceServiceCRUD" as ResourceServiceCRUD
activate ResourceServiceCRUD #DarkSalmon
boundary ResourceRepository
database Biblioteca

Administrator --> ResourceController: Create new resource with areaThemeId, resourceType, Status, name and date
ResourceController --> Resource
Resource-->ResourceServiceCRUD
ResourceServiceCRUD-->ResourceRepository
ResourceRepository-->Biblioteca
Biblioteca --> ResourceRepository
ResourceRepository-->ResourceServiceCRUD
ResourceServiceCRUD-->ResourceController
Administrator <-- ResourceController: Resource creation confirmation

@enduml