@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam actorStyle awesome
mainframe **Modify resource**

actor Administrator
control ResourceController
participant "ResourceServiceCRUD" as ResourceServiceCRUD
activate ResourceServiceCRUD #DarkSalmon
entity Resource
boundary ResourceRepository
database Biblioteca

Administrator --> ResourceController: Consult resources
ResourceController --> ResourceServiceCRUD
ResourceServiceCRUD --> Biblioteca: Get id of a resource
Biblioteca --> ResourceServiceCRUD: Return id of a resource
ResourceServiceCRUD --> ResourceController
ResourceController --> Administrator
Administrator --> ResourceController: Modify resource by id
ResourceController --> ResourceServiceCRUD
ResourceServiceCRUD --> Resource
Resource --> ResourceRepository
ResourceRepository --> Biblioteca
Biblioteca --> ResourceServiceCRUD
ResourceServiceCRUD --> ResourceController
ResourceController --> Administrator: Resource modification confirmation

@enduml